trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: compilation_check
    displayName: Compilation check
    jobs:
      - template: rust/check.yml@templates
        parameters: 
          rust: stable
          all_features: true
  - stage: clippy_check
    displayName: Clippy check
    dependsOn: []
    jobs:
      - template: rust/clippy.yml@templates
        parameters:
          rust: stable
          allow_fail: true
  - stage: cargo_testing
    displayName: Cargo test(s)
    dependsOn: compilation_check
    jobs:
      - template: rust/test.yml@templates
        parameters:
          rust: stable
          id: stable
          cross: false
          allow_fail: false
          test_list:
            - "--all"
  - stage: build_publish
    displayName: Build & publish binary
    jobs:
      - template: rust/publish.yml@templates
        parameters:
          rust: stable
          artifact: 'blog-serve'
  - stage: static_content
    displayName: Publish static files
    jobs:
      - job: static_publish
        steps:
          - task: CopyFiles@2
            inputs:
              Contents: 'static/*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              flattenFolders: true
            displayName: Copy files to staging
          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: static
            displayName: Publish staging

resources:
  repositories:
    - repository: templates
      type: github
      name: bazaah/azure-templates
      endpoint: bazaah