trigger:
- master

stages:
  - stage: compilation_check
    displayName: Compilation check
    jobs:
      - template: rust/check.yml@templates
        parameters: 
          rust: stable
          all_features: true
  - stage: clippy_check
    displayName: Clippy check
    jobs:
      - template: rust/clippy.yml@templates
        parameters:
          rust: stable
          allow_fail: true

resources:
  repositories:
    - repository: templates
      type: github
      name: bazaah/azure-templates
      endpoint: bazaah